In [39]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Carregando o conjunto de dados Iris
iris = datasets.load_iris()

# Montando o DataFrame com as características e o alvo
df = pd.DataFrame(data=np.c_[iris['data'], iris['target']], columns=iris['feature_names'] + ['target'])
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

# Exibindo o DataFrame
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target    species  
0       0.0     setosa  
1       0.0     setosa  
2       0.0     setosa  
3       0.0     setosa  
4       0.0     setosa  
..      ...        ...  
145     2.0  virginica  
146     2.0  virginica  
147     2.0  virginica  
148     2.0  virginica  
149     2.0  virginica  

[150 rows x 6 columns]

In [40]:
# Dividindo os dados em características (X) e alvo (y)
X = df.drop('species', axis=1)
y = df['species']

# Dividindo os dados em conjuntos de treinamento e teste (80% treinamento, 20% teste)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalizando as características
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Exibindo as dimensões dos conjuntos de treinamento e teste
print("-"*50)
print("Dimensões dos conjuntos de treinamento e teste: ")
print("Conjunto de Treinamento (X):   ", X_train.shape)
print("Conjunto de Teste (X):         ", X_test.shape)
print("Conjunto de Treinamento (y):   ", y_train.shape)
print("Conjunto de Teste (y):         ", y_test.shape)

--------------------------------------------------
Dimensões dos conjuntos de treinamento e teste: 
Conjunto de Treinamento (X):    (120, 5)
Conjunto de Teste (X):          (30, 5)
Conjunto de Treinamento (y):    (120,)
Conjunto de Teste (y):          (30,)


In [41]:
# Criar um modelo de Regressão Logística
model = LogisticRegression()

# Treinar o modelo com os dados de treinamento
model.fit(X_train, y_train)

LogisticRegression()

In [46]:
# Fazer previsões com o modelo nos dados de teste
y_pred = model.predict(X_test)

# Calcular a precisão
accuracy = accuracy_score(y_test, y_pred)

# Exibir a matriz de confusão
confusion = confusion_matrix(y_test, y_pred)

# Exibir o relatório de classificação
report = classification_report(y_test, y_pred)

print("\nResultados da Avaliação do Modelo\n")
print("-"*50)
print(f"Precisão: {accuracy:.2f}")

print("-"*50)
print("Matriz de Confusão:")
print(confusion)

print("-"*50)
print("Relatório de Classificação:\n")
print(report)
print("-"*50)


Resultados da Avaliação do Modelo

--------------------------------------------------
Precisão: 1.00
--------------------------------------------------
Matriz de Confusão:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
--------------------------------------------------
Relatório de Classificação:

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

--------------------------------------------------
